import time

import self as self
from selenium import webdriver
from selenium.webdriver import Keys, ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service

s=Service('C:/test/chromedriver.exe')
driver = webdriver.Chrome(service=s)
#Open site
driver.get("https://qa.neapro.site/login")
driver.maximize_window()
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='login-page']/section[@class='login-page']/div[@class='form']//div[@class='login-form']/form//input[@placeholder='Почта']").send_keys("juzigretadu-4779@yopmail.com")
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='login-page']/section[@class='login-page']/div[@class='form']//div[@class='login-form']/form//input[@type='password']").send_keys("10101162")
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='login-page']/section[@class='login-page']//div[@class='login-form']/form//button[@type='submit']").click()
time.sleep(3)
#Fill Pasport
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='content']/div//div[@class='document-tile status']").click()
time.sleep(2)
driver.find_element(By.XPATH, "/html//input[@id='surname']").clear()
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='surname']").send_keys("Охлабыстин")
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='name']").clear()
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='name']").send_keys("Рисик")
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='patronymic']").clear()
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='patronymic']").send_keys("Мухов")
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='passportSeries']").clear()
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='passportSeries']").send_keys("1234")
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='passportNumber']").clear()
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='passportNumber']").send_keys("556622")
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='code']").clear()
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='code']").send_keys("556622")
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='cardId']").clear()
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='cardId']").send_keys("55566677782")
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='birthday']//input[@name='date']").send_keys(Keys.CONTROL+"a")
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='birthday']//input[@name='date']").send_keys("15.11.1990")
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='dateOfIssue']//input[@name='date']").send_keys(Keys.CONTROL+"a")
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='dateOfIssue']//input[@name='date']").send_keys("16.12.2000")
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='issued']").send_keys(Keys.CONTROL+"a")
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='issued']").send_keys("Нурминский")
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='address']/div[@class='vue-dadata__container']//input[@type='text']").send_keys(Keys.CONTROL+"a")
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='address']/div[@class='vue-dadata__container']//input[@type='text']").send_keys("г Москва, ул Городецкая, д 3")
time.sleep(1)
driver.find_element(By.CSS_SELECTOR, ".vue-dadata__suggestions-item").click()
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='phone']").clear()
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='phone']").send_keys("9856325682")
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='content']/div/div[2]//div[@class='buttons']/button[1]").click()
driver.find_element(By.XPATH, "//input[@type='file']").send_keys('D:\\cote.jpg')
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='content']/div/div[2]//button[@class='btn fill']").click()
time.sleep(1)
#Sending a diploma
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='content']/div/div[2]/div[@class='body documents-tiles']/div[2]").click()
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='content']/div/div[2]//div[@class='buttons']/button[1]").click()
time.sleep(1)
driver.find_element(By.XPATH, "//input[@type='file']").send_keys("D:\\cote.jpg")
time.sleep(2)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='content']/div/div[2]//button[@class='btn fill']").click()
time.sleep(2)
#Sending a contract
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='content']/div/div[3]/div[@class='body documents-tiles']/div[@class='document-tile status']").click()
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='content']/div/div[2]//div[@class='buttons']/button[2]").click()
time.sleep(1)
driver.find_element(By.XPATH, "//input[@type='file']").send_keys("D:\\cote.jpg")
time.sleep(2)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='content']/div/div[2]//button[@class='btn fill']").click()
time.sleep(2)
#Sending an application
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='content']/div/div[3]/div[@class='body documents-tiles']/div[2]").click()
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='content']/div/div[2]//div[@class='buttons']/button[1]").click()
time.sleep(1)
driver.find_element(By.XPATH, "//input[@type='file']").send_keys("D:\\cote.jpg")
time.sleep(2)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='content']/div/div[2]//button[@class='btn fill']").click()
time.sleep(2)
#Sending consent
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='content']/div/div[3]/div[@class='body documents-tiles']/div[3]").click()
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='content']/div/div[2]//div[@class='buttons']/button[1]").click()
time.sleep(1)
driver.find_element(By.XPATH, ".//input[@type='file']").send_keys("D:\\cote.jpg")
time.sleep(2)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='content']/div/div[2]//button[@class='btn fill']").click()
time.sleep(2)
#Open site
driver.get("https://adminqa.neapro.site/login")
driver.maximize_window()
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='admin_email']").send_keys("moderat@neapro.ru")
time.sleep(1)
driver.find_element(By.XPATH, "/html//input[@id='admin_password']").send_keys("Aa123456")
time.sleep(1)
driver.find_element(By.XPATH, "//li[@id='admin_submit_action']/input[@name='commit']").click()
time.sleep(1)
#User search
driver.find_element(By.XPATH, "//li[@id='students']/a").click()
time.sleep(1)
driver.find_element(By.XPATH, "//li[@id='users']/a[@href='/users']").click()
time.sleep(1)
dropdown = driver.find_element(By.XPATH, "//div[@id='index_footer']//select")
time.sleep(1)
dropdown.find_element(By.XPATH, "//option[. = '1000']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//a[contains(text(),'2181')]").click()
time.sleep(2)
#Acceptance of documents
driver.find_element(By.XPATH, "/html//div[@id='main_content']/div[5]/div[@class='panel_contents']/table/tbody/tr[1]//div[@class='tag-select-container']/div[1]/span[.='Ожидание']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//input[@type='search']").send_keys("принят")
time.sleep(2)
driver.find_element(By.XPATH, "//input[@type='search']").send_keys(Keys.ENTER)
time.sleep(2)
driver.find_element(By.XPATH, "/html//div[@id='main_content']/div[5]/div[@class='panel_contents']/table/tbody/tr[2]//div[@class='tag-select-container']/div[1]/span[.='Ожидание']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//input[@type='search']").send_keys("принят")
time.sleep(2)
driver.find_element(By.XPATH, "//input[@type='search']").send_keys(Keys.ENTER)
time.sleep(2)
driver.find_element(By.XPATH, "/html//div[@id='main_content']/div[5]/div[@class='panel_contents']/table/tbody/tr[3]//div[@class='tag-select-container']/div[1]/span[.='Ожидание']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//input[@type='search']").send_keys("принят")
time.sleep(2)
driver.find_element(By.XPATH, "//input[@type='search']").send_keys(Keys.ENTER)
time.sleep(2)
driver.find_element(By.XPATH, "/html//div[@id='main_content']/div[5]/div[@class='panel_contents']/table/tbody/tr[4]//div[@class='tag-select-container']/div[1]/span[.='Ожидание']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//input[@type='search']").send_keys("принят")
time.sleep(2)
driver.find_element(By.XPATH, "//input[@type='search']").send_keys(Keys.ENTER)
time.sleep(2)
driver.find_element(By.XPATH, "/html//div[@id='main_content']/div[5]/div[@class='panel_contents']/table/tbody/tr[5]//div[@class='tag-select-container']/div[1]/span[.='Ожидание']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//input[@type='search']").send_keys("принят")
time.sleep(2)
driver.find_element(By.XPATH, "//input[@type='search']").send_keys(Keys.ENTER)
time.sleep(2)
#Open site
driver.get("https://qa.neapro.site/login")
driver.maximize_window()
time.sleep(2)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='login-page']/section[@class='login-page']/div[@class='form']//div[@class='login-form']/form//input[@placeholder='Почта']").send_keys("juzigretadu-4779@yopmail.com")
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='login-page']/section[@class='login-page']/div[@class='form']//div[@class='login-form']/form//input[@type='password']").send_keys("10101162")
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='login-page']/section[@class='login-page']//div[@class='login-form']/form//button[@type='submit']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']/div[@class='static-menu']//a[@href='/cabinet/setting']/img[@alt='avatar']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//div[@id='__layout']//div[@class='main']/div//ul//a[@href='/cabinet/security']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']/div[@class='content-wrapper']/div[@class='main']/div//div[@class='security']//div[@class='body']/div[1]/div[@class='icon']/div[@class='name']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='security']/div[@class='form']//form//input[@name='phone']").clear()
time.sleep(2)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='security']/div[@class='form']//form//input[@name='phone']").send_keys("9253685555")
time.sleep(2)
driver.find_element(By.XPATH, "//div[@id='__layout']//div[@class='main']/div//div[@class='security']/div[@class='form']//form/button[@type='submit']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']//div[@class='main']/div//div[@class='security']/div[@class='form']//img[@alt='X']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']/div[@class='content-wrapper']/div[@class='main']/div//div[@class='security']//div[@class='body']/div[2]/div[@class='icon']/div[@class='name']").click()
time.sleep(2)
driver.find_element(By.XPATH, "/html//input[@id='oldPassword']").send_keys("10101162")
time.sleep(2)
driver.find_element(By.XPATH, "/html//input[@id='newPassword']").send_keys("10101163")
time.sleep(2)
driver.find_element(By.XPATH, "/html//input[@id='confirmPassword']").send_keys("10101163")
time.sleep(2)
driver.find_element(By.XPATH, "//div[@id='__layout']//div[@class='main']/div//div[@class='security']/div[@class='form']//form/button[@type='submit']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']/div[@class='static-menu']//a[@href='/cabinet/setting']/img[@alt='avatar']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//div[@id='__layout']/div[@class='default-layout']/div[@class='static-menu']/div[@class='content']//div[@class='logout_name']").click()
time.sleep(2)